accessing
namingImportant

^ HelpTopic 
		title: 'Naming is Important'
		contents: 'The pattern nodes are that so you can match anything in their place. But their naming is also important as the code get’s mapped to them by name. For example:

	`block value: `@expression value: `@expression

will match only those “value:value:” messages that have exactly the same expressions as both argument. It is like that because we used the same pattern variable name.'