accessing
whatNext

^ HelpTopic 
		title: 'What Next?'
		contents: 'At the moment you can create quality rule that use pattern expression to detect and even automatically fix violations. If you are interested in implementing new rules based on the pattern code I recommend you to read the documentation about Renraku, the quality model. Just DoIt:

	HelpBrowser openOn: RenrakuHelp

Especially read: Rules > Creating Rules > Special Rules > ReNodeMatchRule'